mysql:
  image: hypriot/rpi-mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  volumes:
    - /media/usbraid/docker/mysql/data:/var/lib/postgresql/data
    - /media/usbraid/docker/mysql/etc:/etc/mysql/conf.d
  ports:
    - "3306:3306"
  restart: always

mantisbt:
  image: paperinik/rpi-mantisbt:latest
  environment:
    - DATABASE_URL=jdbc://mantis:mantis@192.168.1.30:3306/bugtracker
  ports:
    - "9400:80"
  links:
    - mysql
  restart: always
